# Generated by Django 3.0.3 on 2020-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_editor_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='image', upload_to='articles/'),
        ),
    ]
