# Generated by Django 3.0.3 on 2020-02-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='img1.png', upload_to='articles/'),
        ),
    ]
